# Generated by Django 2.2.16 on 2022-12-01 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221201_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='user',
            field=models.OneToOneField(help_text='Инстанс связанного юзера.', on_delete=django.db.models.deletion.CASCADE, related_name='auth', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
