# Generated by Django 2.2.16 on 2022-12-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221201_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Статус текущего аккаунта - активирован или нет.', verbose_name='Активный/неактивный.'),
        ),
    ]
